Create xdebug-and-phpstorm.md
Varying-Vagrant-Vagrants/varyingvagrantvagrants.org pull request #174
Opened 2020-05-06 16:39 UTC by theMikeD

2020-05-07 14:33 UTC, Mte90 requested changes

2020-05-07 14:33 UTC, Mte90 commented on docs/en-US/references/xdebug-and-phpstorm.md
> +   - PHP language level: 7.3
We need to write that is better to align this value with the one inside the `config.yml` for the specific domain. If a custom one is not defined the value is the php default version in the machine that now is php 7.2.

2020-05-08 10:23 UTC, tomjn commented
I've made some adjustments so it would work if it was merged, and fixed some formatting stuff where block quotes were used for emphasis, etc, but I need to sit down and properly read through, there's some stylistic changes that'll be needed so it fits in with the rest of the site better.

@theMikeD thanks for getting us most of the way :) Feel free to take bits back for internal use

2020-05-08 14:06 UTC, theMikeD commented
I figured the tone would have to change but you're more than welcome!

2020-06-18 13:14 UTC, tomjn approved these changes

2020-06-18 13:14 UTC, merged

2020-06-18 13:15 UTC, tomjn commented
It could use some adjustment still, but it's useful enough to be on the site. I'd need a PHPStorm install to make more progress